### PR TITLE
Prevent removal of deprecated request/response attribute from creating a breaking change

### PR DESCRIPTION
**Pull request by pkunze**
I tried to implement it according to the discussion in #97
Please have a critical look at it as this (Java) is foreign territory to me. 🔥

### CODE REVIEW

**Review by galovics — CHANGES_REQUESTED** [review]
The changes are looking good, the only thing I'm missing is an integration test comparing 2 swaggers. Please take a look at the https://github.com/redskap/swagger-brake/tree/master/swagger-brake/src/test/java/io/redskap/swagger/brake/integration folder.

**Comment by galovics** [comment]
Plus I just approved the run of the integration tests and it seems there are failures, please take a look.

**Comment by pkunze** [comment]
Alright. I too noticed failing tests, however, those seemed to be broken even without my changes. 
However, I will take a look no matter what. :)
Thank you for takin the time!

**Comment by galovics** [comment]
@pkunze strange. I'll check it soon myself but let me know if you're stuck somewhere.

**Comment by pkunze** [comment]
@galovics i managed to fix those in the meantime. now im left with some remainig (correct) errors that im currently working on. 
Those are actually errors i caused 🤭
No need for you to step in (so far).

**Comment by galovics** [comment]
@pkunze I think the behavior is correct i.e. to report 3 attributes being removed. Indeed the schema for the Category object did not change but remember, swagger-brake doesn't report breaking/non-breaking changes on the schemas but on the APIs.

Imagine you had this API:
```
POST /category
{
	"category": {
		"id": 1,
		"name": "something"
	}
}
```
And then you change your API definition to accept only this:
POST /category
{
	"id": 1,
	"name": "something"
}
```
In this case, your API has been changed, not the schema object you used to represent the category. 
The category attribute has been removed along with category.id and category.name. But this relates to the API, not the schema as I said.

**Comment by galovics** [comment]
@pkunze please rebase your branch from master. I've made a commit to fix the build errors.

**Pull request merged**
